"""Add indexes to foreign keys

Revision ID: 20cb291f1ef7
Revises: c8d9e0f1a2b3
Create Date: 2026-02-21 09:55:37.646295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cb291f1ef7'
down_revision: Union[str, None] = 'c8d9e0f1a2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_groups_created_by'), 'groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_line_item_assignments_line_item_id'), 'line_item_assignments', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_line_item_assignments_user_id'), 'line_item_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_line_items_receipt_id'), 'line_items', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_payments_paid_by'), 'payments', ['paid_by'], unique=False)
    op.create_index(op.f('ix_payments_receipt_id'), 'payments', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipts_group_id'), 'receipts', ['group_id'], unique=False)
    op.create_index(op.f('ix_receipts_uploaded_by'), 'receipts', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_settlements_from_user'), 'settlements', ['from_user'], unique=False)
    op.create_index(op.f('ix_settlements_group_id'), 'settlements', ['group_id'], unique=False)
    op.create_index(op.f('ix_settlements_to_user'), 'settlements', ['to_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlements_to_user'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_group_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_from_user'), table_name='settlements')
    op.drop_index(op.f('ix_receipts_uploaded_by'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_group_id'), table_name='receipts')
    op.drop_index(op.f('ix_payments_receipt_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_by'), table_name='payments')
    op.drop_index(op.f('ix_line_items_receipt_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_item_assignments_user_id'), table_name='line_item_assignments')
    op.drop_index(op.f('ix_line_item_assignments_line_item_id'), table_name='line_item_assignments')
    op.drop_index(op.f('ix_groups_created_by'), table_name='groups')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    # ### end Alembic commands ###
